### ISSUE TITLE
Opera 11 Date.prototype passes the isDate test

### ISSUE THREAD

**Issue by Xotic750** [inspect-js/is-date-object#3]
I came across this while validating whether a date is valid for display with `inspect: test GH-1941`, by checking `Date#getTime` result for `isNaN`. This seems common for many older engines, while newer engines are fine, either because they use `[object Object]` or they have support for `toStringTag` and therefore take the `try...catch` route. I'm sure that this can be a problem with other `isSomething` methods too, but with Date it is particularly problematic due the the validation performed, which throws. Perhaps the stringTag of the prototype could be checked initially and choose to us the `try..catch` route if it matches `[object Date]`?
```js
var x = Date.prototype;
if (isDate(x)) {
  console.log(Object.prototype.toString.call(x)); // '[object Date]'
  var time = x.getTime(); // Uncaught TypeError: this is not a Date object.
  console.log(isNaN(x));
}
```

**Comment by ljharb** [comment]
It's supposed to; prior to ES6, `Date.prototype` was allowed to be exotic, and most engines implemented it as such.

If you want to exclude the current realm's `Date.prototype`, you could certainly do `x !== Date.prototype && !isDate(x)` - but it'd be impossible for this module to cross-realm exclude `Date.prototype`, and it wouldn't be correct anyways.

In summary, this package checks for the internal Date slots; if `Date.prototype` has them, it should return `true`.

**Comment by Xotic750** [comment]
Thanks. No problem, I can work around it, just wanted to be sure to report it as it can catch you unexpectedly. ;)
